name: "Terraform"

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

env:
   TF_VAR_project: ${{ secrets.PROJECT }}
   TF_VAR_credentials_file: ${{ secrets.CREDENTIALS }}

jobs:
   terraform:
      name: "Terraform"
      runs-on: ubuntu-latest
      defaults:
         run:
            shell: bash
            working-directory: ./terraform

      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Setup terraform
           uses: hashicorp/setup-terraform@v1

         - name: Configure Google Cloud credentials
           env:
              GCP_CREDENTIALS_JSON: ${{ secrets.CREDENTIALS }}
           run: echo "$GCP_CREDENTIALS_JSON" > gcp_credentials.json

         - name: Initialize Terraform
           env:
              GCP_CREDENTIALS_JSON: ${{ secrets.CREDENTIALS }}
           run: |
              terraform init \
                -backend-config="bucket=tf-state-prod" \
                -backend-config="prefix=terraform/state" \
                -backend-config="credentials=~/gcp_credentials.json"

         - name: Terraform Format
           run: terraform fmt -check

         - name: Terraform Plan
           run: terraform plan -input=false

         - name: Terraform Apply
           if: github.ref == 'refs/heads/main'
           run: terraform apply -auto-approve -input=false
